### ISSUE TITLE
A question about /persistence/store

### ISSUE THREAD

**Issue by wwayne** [emmenko/redux-react-router-async-example#30]
First thanks for such a great example.
I have one problem when reading and learning your code that really confused me, so I look to you for help.

In `/persistence/store`, the return of the function is 

```
return Object.assign({}, store, {
      dispatch (action) {
        store.dispatch(action)
        ...
      }
    })
```

And I have no idea about the last params in Object.assign(),  why there is function inside the object? where is dispatch comes from? 

It may be a basic question of JS feature, if so, could you tell me where to find the document, I can check myself. 
Thanks a lot

**Comment by emmenko** [comment]
So this file is basically a [Store enhancer](https://github.com/rackt/redux/blob/master/docs/Glossary.md#store-enhancer) that allows to [combine multiple stores](https://github.com/emmenko/redux-react-router-async-example/blob/master/lib/utils/configure-store.js#L9-L14) like a middleware.

In my case I just want to "enhance" the [`dispatch` function](https://github.com/rackt/redux/blob/2c473534fcf27f80db4b7f1cb177efa007dfced1/src/createStore.js#L94) in order to do something whenever an action is dispatched. As you can see I save some information from the `store` in localstorage. 

It's just a simple use case for a store enhancer. You might not need to use it, but can be quite useful for such use cases. The `devtools` also use store enhancers.

I hope this answers your question :)

PS: I need to provide some jsdoc anyway (ref #18)

**Comment by wwayne** [comment]
Ok, I think I get you : )
For those who also unclear about what `{ dispatch() {} }` is, this is an **ES6** feature:
`{ dispatch() {} }` = `{ dispatch: function() {} }` 

Anyway, Thanks :+1:
