### ISSUE TITLE
actionhandlers

### ISSUE THREAD

**Issue by juanda99** [emmenko/redux-react-router-async-example#55]
Just starting with Redux, without flux knowledge.
I can't get the meaning of actionHandlers, where is it from?
No action creators?

Anyway... What's the meaning of the underscore parameter _?

```
const actionHandlers = {
  [constants.LOGGED_IN]: (_, action) => action.payload,
  [constants.LOG_OUT]: () => ({ token: null }),
  [constants.LOCALE_SWITCHED]: (_, action) => ({ locale: action.payload })
....
```

Thank you very much for your hard work.

**Comment by revolunet** [comment]
from my undestanding : action creators trigger action handlers which are "state reducers"

the underscore is just a placeholder, by default its `(state, action)`

**Comment by emmenko** [comment]
@juanda99 basically it's how @revolunet said ;)

> I can't get the meaning of actionHandlers, where is it from?

To explain it a bit more, reducers are functions that return a (new) state given some actions. Usually you probably do that with a `switch` case by checking the `action.type`. But you can also use a simple hash map with the action type as the key. This is what `actionHandlers` are and `createReducer` does (it's function composition).
As for the name "actionHandlers", as it implies it _handles_ actions :)

> No action creators?

On the other hand, **action creators** are functions that will eventually **trigger** an action, which will be then _handled_ by the reducers.

> What's the meaning of the underscore parameter _?

It's meant to be a placeholder since the argument it's not used in the related case, as you are interested in the second argument. But this is rather a personal choice, if it's less confusing to you simply declare the arguments with names as usual.

Hope this helps you further ;)
