### ISSUE TITLE
React-intl, locale stored on LocalStorage

### ISSUE THREAD

**Issue by sirrodgepodge** [emmenko/redux-react-router-async-example#58]
First off, thank you so much for publishing this, relatively new to React and need to implement React-Intl in ES6, this repo is a lifesaver.

Particularly helpful is the fact that this example combines React Router with React-Intl, something sorely missing from the React-Intl "examples" section (read all of this: https://github.com/rackt/react-router/issues/484 and then realized this was for ES5 + React-Intl 1.x).

Second, one question that I still have when looking through your app, why did you store the current "locale" in LocalStorage instead of a traditional "store"?  

Perhaps I'm missing something Redux-related.

**Comment by emmenko** [comment]
Hey, glad that helps ;)

First of all I think we need to clarify the "traditional store" meaning. If you mean a store a-la Flux, well you don't need / have those in Redux.
In Redux you have basically a state object for the entire application. You can consider this as your "store". Whenever you dispatch an action, the reducer functions that you have mapped for each action will return a "new state" object with the related changes. You **don't mutate** anything in Redux.

If you haven't I would really recommend to really through all of the Redux documentation, it's worth it!
http://rackt.org/redux/index.html

In this app I have a 2 state objects: `application` and `github`. 
https://github.com/emmenko/redux-react-router-async-example/blob/master/lib/reducers/index.js

The Redux state (or store) will then be something like `{ application: {...}, github: {...} }`

The `application` state object will have then a shape described here
https://github.com/emmenko/redux-react-router-async-example/blob/master/lib/reducers/application.js#L4-L14

You see that there is a `locale` key, which gets updated when I dispatch the `LOCALE_SWITCHED` action.

In this example I'm using `localStorage` to persist the `application` state so that when I reload the page, the application starts with my previous state.

I hope this helps you a bit further ;)

**Comment by sirrodgepodge** [comment]
Ahhh gotcha, thank you for your quick response!

One last question for you.  How are you using React-Intl components (for example: https://github.com/emmenko/redux-react-router-async-example/blob/a09a0ee7c203341c05d74ba025752873e0fdfb21/lib/components/pages/GithubStargazers.js)

**Comment by sirrodgepodge** [comment]
Thank you for your quick response, yes Redux seems very intriguing, your app is helping me understand it quite a bit :)
